[package]
name = "secure_messaging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2rs = "0.2"
rpassword = "5"
rusqlite = "0.25"
rand = "0.8"
hex = "0.4"
chrono = "0.4"
